# Site settings
title: tanukilabs
email: copykatt@yandex.com
description: >
    tanukilabs is a small independent indie game and mobile development studio
    located in Germany and Switzerland. It was founded in late 2012. On this page,
    we write about current projects and other subjects of interest.
baseurl: ""
url: "http://tanukilabs.github.io/"
github_username: tanukilabs
encoding: utf-8

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
