# Site information
title: tanukilabs
author: copykatt
tagline: lelel
email: copykatt@yandex.com
description: >
    tanukilabs is a small independent indie game and mobile development studio
    located in Germany and Switzerland. It was founded in late 2012. On this page,
    we write about current projects and other subjects of interest.
baseurl: ""
url: "http://tanukilabs.github.io/"

encoding: utf-8

# Personal information and site tools info:
github_username: tanukilabs

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
